### ISSUE TITLE
网络扒手？

### ISSUE THREAD

**Issue by hishis** [mxdh/Forum-Master-Discuz-#1]
# 盗取别人的代码还删除了原作者的版权信息，还要脸吗？
### 原版地址
[https://greasyfork.org/scripts/400250](https://greasyfork.org/scripts/400250)

**Comment by mxdh** [comment]
请看readme.md（自述文档里也有）
**This project is based on hostname‘ [Forum Master・Discuz!](https://greasyfork.org/zh-CN/scripts/400250-forum-master-discuz), and complies with GPL-3.0**

我也没有删除版权信息
在main.js的63行
```
    //This is the original author's statement:
    /**
     * Forum Master・Discuz! - https://greasyfork.org/scripts/400250
     *
     * == BEGIN LICENSE ==
     *
     * Open name: Forum Master・Discuz!
     * Open home: https://greasyfork.org/scripts/400250
     *
     * Licensed under the terms of any of the following licenses at your
     * choice:
     *
     * 1. GPL - GNU General Public License
     *    https://www.gnu.org/licenses/gpl-3.0.html
     *
     * 2. MPL - Mozilla Public License
     *    https://www.mozilla.org/MPL/2.0/
     *
     * Copyright statement is prohibited from modification and must be retained.
     *
     * == END LICENSE ==
     */
```
如果你认为是我后来加的，大可看看commit

我的行为是遵守GPL-3.0和MPL-2.0的


如果你说那个home按钮的话，我当成广告删掉了（即使不算广告，那也是多余的东西吧？，GPL和MPL可没说要把这种东西留下来）

**Comment by mxdh** [comment]
还有问题吗？

**Comment by mxdh** [comment]
还有问题的话尽管说，我可以reopen这个issue，我们来讲讲清楚

**Comment by hishis** [comment]
> 改进 -> 使用Ctrl+Enter或Alt+S快速回帖

项目本身就支持 Ctrl+Enter 或 Alt+S 快速回帖并强制显示，为何这项功能在你的**自述文件**中的**改进列表**里面？

> 改进 -> 去掉了原项目中的广告按钮

**访问主页按钮**方便用户访问脚本发布页查看项目介绍和更新内容，**群组聊天按钮**方便用户反馈`Bug`、`意见`和`建议`。
**去掉主页按钮**你就写**去掉主页按钮**，**去掉群组聊天按钮**你就写**去掉群组聊天按钮**。怎么就成了**广告**了呢？

---

另外，项目已更换为更为宽松的 MPL 2.0 开源许可。

**Comment by mxdh** [comment]
> 
> 
> > 改进 -> 使用Ctrl+Enter或Alt+S快速回帖
> 
> 项目本身就支持 Ctrl+Enter 或 Alt+S 快速回帖并强制显示，为何这项功能在你的**自述文件**中的**改进列表**里面？
> 
> > 改进 -> 去掉了原项目中的广告按钮
> 
> **访问主页按钮**方便用户访问脚本发布页查看项目介绍和更新内容，**群组聊天按钮**方便用户反馈`Bug`、`意见`和`建议`。
> **去掉主页按钮**你就写**去掉主页按钮**，**去掉群组聊天按钮**你就写**去掉群组聊天按钮**。怎么就成了**广告**了呢？
> 
> 另外，项目已更换为更为宽松的 MPL 2.0 开源许可。

emm，改进是一个列表，那项不在列表里（Markdown的无序列表）

这个应该是作者所说的隐藏功能，我为了方便使用者，就单独列出来了

MPL 2.0上面我也写了，作者也同意使用GPL或者MPL，所以我用了GPL

广告的话。。。因为我个人有点洁癖，而且那个聊天群组的网址也比较敏感（你懂的），我就直接写广告了

抱歉，这是我写的不明白
等一会我改一下说明，你可以亲自来确认，如果觉得没问题了，就close掉吧，我要去上课了

**不过也不至于说我删掉了版权信息，是网络扒手吧。。。**

**Comment by hishis** [comment]
我开这个**话题**说你是网络扒手的原因就是我上面说的你把**已有功能**（_热键功能_）加入**改进功能**列表。
版权问题是我之前没有看到你保留了版权。抱歉，这是一场误会。

**Comment by mxdh** [comment]
嗯，感谢理解
那我close了
